import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 * ---------------------------------------------------------------------
 * Warehouse Application
 * The Item Entry screen to process item entry transactions
 * @author Alvaro Morales
 * @date 13/07/2010
 * @school Markham College
 * @IDE Eclipse SDK
 * @computer IBM ThinkPad R52
 * ---------------------------------------------------------------------
 */
public class ItemEntry extends javax.swing.JPanel {

	/**
	 * Start of the code generated using CloudGarden's Jigloo SWT/Swing GUI Builder
	 */

	/**
	 * GUI components generated by Jigloo
	 */

	private JLabel lblItemEntry;
	private JTable tblQuantities;
	private JLabel lblQuantitiesInfo;
	private JLabel lblQuantities;
	private JScrollPane scpQuantities;
	private JButton btnFinish;
	private JSeparator spEntryList;
	private JTextField txtDeliveredBy;
	private JLabel lblRequestedBy;
	private JTextField txtDate;
	private JLabel lblDate;
	private JTextField txtReceivedBy;
	private JLabel lblDispatchedBy;
	private JTextField txtProof;
	private JLabel lblRequiredFields;
	private JLabel lblItemExitVoucher;

	/**
	 * An ArrayList of items to process
	 */
	private ArrayList itemsToProcess;

	/**
	 * The user that logged in
	 */
	private User user;

	/**
	 * The current date
	 */
	private GregorianCalendar date;


	{
		//Set Look & Feel
		try {
			javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
		} catch(Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * Constructs a new ItemEntry object
	 * @param user - the user that logged in
	 * @param itemsToProcess - an ArrayList of items to process
	 */
	public ItemEntry(User user, ArrayList itemsToProcess) {
		super();
		this.user = user;
		date = new GregorianCalendar();
		this.itemsToProcess = itemsToProcess;
		initGUI();
	}

	/**
	 * Method generated by Jigloo to initialize GUI components
	 */
	private void initGUI() {
		try {
			this.setPreferredSize(new java.awt.Dimension(800, 500));
			this.setLayout(null);
			{
				lblItemEntry = new JLabel();
				this.add(lblItemEntry);
				lblItemEntry.setText("4. Item Entry");
				lblItemEntry.setFont(new java.awt.Font("Dialog",1,14));
				lblItemEntry.setBounds(12, 12, 96, 16);
			}
			{
				lblItemExitVoucher = new JLabel();
				this.add(lblItemExitVoucher);
				lblItemExitVoucher.setText("Proof of Reception No.* :");
				lblItemExitVoucher.setBounds(36, 56, 132, 16);
				lblItemExitVoucher.setSize(137, 16);
			}
			{
				lblRequiredFields = new JLabel();
				this.add(lblRequiredFields);
				lblRequiredFields.setText("Fields marked with an * are required");
				lblRequiredFields.setFont(new java.awt.Font("Dialog",0,10));
				lblRequiredFields.setBounds(12, 28, 205, 16);
			}
			{
				txtProof = new JTextField();
				this.add(txtProof);
				txtProof.setBounds(180, 54, 188, 20);
				txtProof.setSize(206, 24);
				txtProof.setDocument(new TextFieldDigitLimit(8));
			}
			{
				lblDispatchedBy = new JLabel();
				this.add(lblDispatchedBy);
				lblDispatchedBy.setText("Received By:");
				lblDispatchedBy.setBounds(457, 56, 72, 16);
			}
			{
				txtReceivedBy = new JTextField();
				this.add(txtReceivedBy);
				txtReceivedBy.setBounds(541, 54, 206, 20);
				txtReceivedBy.setEditable(false);
				txtReceivedBy.setSize(206, 24);
				txtReceivedBy.setText(user.getUsername());
			}
			{
				lblDate = new JLabel();
				this.add(lblDate);
				lblDate.setText("Date:");
				lblDate.setBounds(500, 94, 29, 16);
			}
			{
				txtDate = new JTextField();
				this.add(txtDate);
				txtDate.setBounds(541, 90, 206, 24);
				txtDate.setEditable(false);
				int day = date.get(Calendar.DAY_OF_MONTH);
				int month = date.get(Calendar.MONTH) + 1;
				int year = date.get(Calendar.YEAR);
				txtDate.setText(day + "/" + month + "/" + year);
			}
			{
				lblRequestedBy = new JLabel();
				this.add(lblRequestedBy);
				lblRequestedBy.setText("Delivered By* :");
				lblRequestedBy.setBounds(91, 94, 82, 16);
			}
			{
				txtDeliveredBy = new JTextField();
				this.add(txtDeliveredBy);
				txtDeliveredBy.setBounds(180, 90, 206, 24);
			}
			{
				spEntryList = new JSeparator();
				this.add(spEntryList);
				spEntryList.setBounds(12, 127, 776, 10);
			}
			{
				scpQuantities = new JScrollPane();
				this.add(scpQuantities);
				scpQuantities.setBounds(36, 188, 725, 256);
				{
					TransactionProcessingTableModel tblQuantitiesModel = 
						new TransactionProcessingTableModel(itemsToProcess);
					tblQuantities = new JTable();
					scpQuantities.setViewportView(tblQuantities);
					tblQuantities.setModel(tblQuantitiesModel);
					tblQuantities.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
					tblQuantities.addMouseListener(new MouseAdapter() {
						public void mouseClicked(MouseEvent e) {
							if (e.getClickCount() == 2) {
								JTable tblResults = (JTable)e.getSource();
								int row = tblResults.getSelectedRow();
								TransactionProcessingTableModel model = 
									(TransactionProcessingTableModel) tblQuantities.getModel();
								Item item = (Item) model.getSearchResults().get(row);
								ItemDescription description = new ItemDescription(item);
								description.setVisible(true);
							}
						}
					});

					//Set Column "Item ID" width
					int vColIndex = 0;
					TableColumn colID = tblQuantities.getColumnModel().getColumn(vColIndex);
					int width = 100;
					colID.setPreferredWidth(width);

					//Set Column "Item Name" width
					TableColumn colName = tblQuantities.getColumnModel().getColumn(1);
					colName.setPreferredWidth(308);

					//Set Column "UM" width
					TableColumn colUM = tblQuantities.getColumnModel().getColumn(2);
					colUM.setPreferredWidth(50);

					//Set Column "In Stock" width
					TableColumn colStock = tblQuantities.getColumnModel().getColumn(3);
					colStock.setPreferredWidth(100);

					//Set Column "Quantity to be Entered" width
					TableColumn colQuantity = tblQuantities.getColumnModel().getColumn(4);
					colQuantity.setPreferredWidth(150);

				}
			}
			{
				btnFinish = new JButton();
				this.add(btnFinish);
				btnFinish.setText("Finish");
				btnFinish.setBounds(672, 456, 89, 26);
				btnFinish.addActionListener(new ActionListener() {
					public void actionPerformed (ActionEvent e){
						performTransactionProcessing();
					}
				});
			}
			{
				lblQuantities = new JLabel();
				this.add(lblQuantities);
				lblQuantities.setText("5. Quantities");
				lblQuantities.setFont(new java.awt.Font("Dialog",1,14));
				lblQuantities.setBounds(12, 143, 96, 16);
			}
			{
				lblQuantitiesInfo = new JLabel();
				this.add(lblQuantitiesInfo);
				lblQuantitiesInfo.setText("Fill the 'Quantity' column for each item to be entered into stock");
				lblQuantitiesInfo.setFont(new java.awt.Font("Dialog",0,10));
				lblQuantitiesInfo.setBounds(12, 160, 631, 16);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * End of the code generated using CloudGarden's Jigloo SWT/Swing GUI Builder
	 */

	/**
	 * Checks that the input is correct, and if so calls the methods to process the transactions
	 */
	public void performTransactionProcessing(){
		if(isCorrectInput()){
			processAllTransactions();
			JOptionPane.showMessageDialog(this, "Transactions successfully processed", 
					"Success", JOptionPane.INFORMATION_MESSAGE);
			ChangeScreen.setBlankScreen(user);
		} else {
			JOptionPane.showMessageDialog(this, "Some fields are missing or incorrect", "Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * Processes all the transactions
	 */
	public void processAllTransactions(){
		TransactionProcessingTableModel model = (TransactionProcessingTableModel)tblQuantities.getModel();
		TransactionRecord[] transactionsToProcess = new TransactionRecord[model.getRowCount()];

		for(int i=0;i<transactionsToProcess.length;i++){
			transactionsToProcess[i] = new TransactionRecord();
			transactionsToProcess[i].setType(ApplicationConstants.ITEM_ENTRY);	//screen deals with item entry
			transactionsToProcess[i].setDocument(txtProof.getText());
			transactionsToProcess[i].setDate(this.date);
			transactionsToProcess[i].setWarehouseWorker(txtReceivedBy.getText());
			transactionsToProcess[i].setThirdParty(txtDeliveredBy.getText());
			transactionsToProcess[i].setQuantity(((Integer)model.getValueAt(i, 4)).intValue());
			transactionsToProcess[i].setItem((Item)model.getSearchResults().get(i));
			transactionsToProcess[i].processTransaction();
		}

	}

	/**
	 * Checks if all the necessary fields have been filled in
	 * @return true if all fields have been filled in, else false
	 */
	public boolean isCorrectInput(){
		TransactionProcessingTableModel model = (TransactionProcessingTableModel)tblQuantities.getModel();
		boolean isComplete = true;

		for(int i=0;i<model.getRowCount();i++){
			TransactionRecord record = model.getTransactions()[i];
			if(record.getQuantity() <= 0){
				isComplete = false;
				break;
			}
		}

		if(txtProof.getText().equals("") || txtDeliveredBy.getText().equals("") || !isComplete){
			return false;
		} else {
			return true;
		}
	}

	/**
	 * Opens the description of a selected item (row in a table)
	 * @param row - the selected row index
	 */
	public void openItemDescription(int row){
		TransactionProcessingTableModel model = (TransactionProcessingTableModel)tblQuantities.getModel();
		Item item = (Item)model.getSearchResults().get(row);
		ItemDescription description = new ItemDescription(item, user);
		description.setVisible(true);
	}

}
