import java.awt.BorderLayout;
import javax.swing.*;

/**
 * ---------------------------------------------------------------------
 * Warehouse Application
 * Constructs a FileChooser to select an item image from disk
 * @author Alvaro Morales
 * @date 21/06/2010
 * @school Markham College
 * @IDE Eclipse SDK
 * @computer IBM ThinkPad R52
 * ---------------------------------------------------------------------
 */
public class OpenFile extends javax.swing.JFrame {

	/**
	 * Start of the code generated using CloudGarden's Jigloo SWT/Swing GUI Builder
	 */
	
	/**
	 * The FileChooser object
	 */
	private JFileChooser flcOpenFile;
	
	{
		//Set Look & Feel
		try {
			javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
		} catch(Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * Constructs a new OpenFile object
	 */
	public OpenFile() {
		super();
		initGUI();
	}
		
	/**
	 * Method generated by Jigloo to initialize GUI components
	 */
	private void initGUI() {
		try {
			setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
			this.setTitle("Select Image");
			{
				flcOpenFile = new JFileChooser();
				getContentPane().add(flcOpenFile, BorderLayout.CENTER);
			}
			pack();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
