import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.event.*;

/**
 * ---------------------------------------------------------------------
 * Warehouse Application
 * Constructs the WarehouseMenuBar object
 * @author Alvaro Morales
 * @date 13/06/2010
 * @school Markham College
 * @IDE Eclipse SDK
 * @computer IBM ThinkPad R52
 * ---------------------------------------------------------------------
 */
public class WarehouseMenuBar extends javax.swing.JMenuBar {

	/**
	 * Start of the code generated using CloudGarden's Jigloo SWT/Swing GUI Builder
	 */

	/**
	 * GUI components generated by Jigloo
	 */

	private JMenuItem mnuManageUsers;
	private JSeparator spFileMenu;
	private JMenuItem mnuAccountSettings;
	private JMenuItem mnuAbout;
	private JMenu mnuHelp;
	private JMenu mnuAdmin;
	private JMenuItem mnuCreateNewItem;
	private JMenuItem mnuExit;
	private JMenuItem mnuReturn;
	private JMenuItem mnuItemExit;
	private JMenuItem mnuItemEntry;
	private JMenu mnuStockMaintenance;
	private JMenuItem mnuItemSearch;
	private JMenu mnuItemRecords;
	private JMenu mnuFile;

	/**
	 * The user that logged in
	 */
	private User user;

	/**
	 * Constructs a WarehouseMenuBar object
	 * @param user - the user that logged in
	 * @param main - the MainScreen object that holds the menu bar
	 */
	public WarehouseMenuBar(User user, MainScreen main){

		final MainScreen MAIN_SCREEN = main;
		this.user = user;

		{
			mnuFile = new JMenu();
			this.add(mnuFile);
			mnuFile.setText("File");
			{
				mnuAccountSettings = new JMenuItem();
				mnuFile.add(mnuAccountSettings);
				mnuAccountSettings.setText("Account Settings");
				mnuAccountSettings.addActionListener(new ActionListener() {
					public void actionPerformed (ActionEvent e){
						openAccountSettings();
					}
				});
			}
			{
				spFileMenu = new JSeparator();
				mnuFile.add(spFileMenu);
			}
			{
				mnuReturn = new JMenuItem();
				mnuFile.add(mnuReturn);
				mnuReturn.setText("Return to Main Menu");
				mnuReturn.addActionListener(new ActionListener(){
					public void actionPerformed(ActionEvent e){
						ChangeScreen.setBlankScreen(getUser());
					}
				});
			}
			{
				mnuExit = new JMenuItem();
				mnuFile.add(mnuExit);
				mnuExit.setText("Exit");
				mnuExit.addActionListener(new ActionListener(){
					public void actionPerformed(ActionEvent e){
						System.exit(0);
					}
				});
			}
		}
		{
			mnuItemRecords = new JMenu();
			this.add(mnuItemRecords);
			mnuItemRecords.setText("Item Records");
			{
				//Construct items only relevant to user permissions
				if(user.isEntry() || user.isAdmin()){
					mnuCreateNewItem = new JMenuItem();
					mnuItemRecords.add(mnuCreateNewItem);
					mnuCreateNewItem.setText("New Item");
					mnuCreateNewItem.setIcon(new ImageIcon(getClass().getClassLoader().getResource(
							ApplicationConstants.CREATE_ITEM_ICON)));
					mnuCreateNewItem.addActionListener(new ActionListener(){
						public void actionPerformed(ActionEvent e){
							ChangeScreen.setCreateNewItemScreen(getUser());
						}
					});
				}

			}
			{
				mnuItemSearch = new JMenuItem();
				mnuItemRecords.add(mnuItemSearch);
				mnuItemSearch.setText("Item Search");
				mnuItemSearch.setIcon(new ImageIcon(getClass().getClassLoader().getResource(
						ApplicationConstants.ITEM_ENQUIRY_ICON)));
				mnuItemSearch.addActionListener(new ActionListener(){
					public void actionPerformed(ActionEvent e){
						ChangeScreen.setItemSearchScreen(getUser());
					}
				});
			}
		}
		{
			mnuStockMaintenance = new JMenu();
			this.add(mnuStockMaintenance);
			mnuStockMaintenance.setText("Stock Maintenance");
			{
				//Construct items only relevant to user permissions
				if(user.isEntry() || user.isAdmin()){
					mnuItemEntry = new JMenuItem();
					mnuStockMaintenance.add(mnuItemEntry);
					mnuItemEntry.setText("Stock Entry");
					mnuItemEntry.setIcon(new ImageIcon(getClass().getClassLoader().getResource(
							ApplicationConstants.ITEM_ENTRY_ICON)));
					mnuItemEntry.addActionListener(new ActionListener(){
						public void actionPerformed(ActionEvent e){
							ChangeScreen.setMultipleItemSearchScreen(
									getUser(), ApplicationConstants.ITEM_ENTRY);
						}
					});
				}

			}
			{
				//Construct items only relevant to user permissions
				if(user.isExit() || user.isAdmin()){
					mnuItemExit = new JMenuItem();
					mnuStockMaintenance.add(mnuItemExit);
					mnuItemExit.setText("Item Exit");
					mnuItemExit.setIcon(new ImageIcon(getClass().getClassLoader().getResource(
							ApplicationConstants.ITEM_EXIT_ICON)));
					mnuItemExit.addActionListener(new ActionListener(){
						public void actionPerformed(ActionEvent e){
							ChangeScreen.setMultipleItemSearchScreen(
									getUser(), ApplicationConstants.ITEM_EXIT);
						}
					});
				}

			}
		}
		{
			//Construct items only relevant to user permissions
			if(user.isAdmin()){
				mnuAdmin = new JMenu();
				this.add(mnuAdmin);
				mnuAdmin.setText("Admin");
				{
					mnuManageUsers = new JMenuItem();
					mnuAdmin.add(mnuManageUsers);
					mnuManageUsers.setText("Manage Users");
					mnuManageUsers.addActionListener(new ActionListener(){
						public void actionPerformed(ActionEvent e){
							ChangeScreen.setManageUsersScreen(getUser());
						}
					});
				}
			}

		}
		{
			mnuHelp = new JMenu();
			this.add(mnuHelp);
			mnuHelp.setText("Help");
			{
				mnuAbout = new JMenuItem();
				mnuHelp.add(mnuAbout);
				mnuAbout.setText("About");
				mnuAbout.addActionListener(new ActionListener() {
					public void actionPerformed (ActionEvent e){
						displayAboutMessage();
					}
				});
			}
		}

	}

	/**
	 * End of the code generated using CloudGarden's Jigloo SWT/Swing GUI Builder
	 */

	/**
	 * Gets the user that logged in
	 * @return the user that logged in
	 */
	public User getUser(){
		return user;
	}

	/**
	 * Opens the AccountSettings screen
	 */
	public void openAccountSettings(){
		AccountSettings settings = new AccountSettings(user);
		settings.setVisible(true);
		settings.setLocation(60, 180);
	}

	/**
	 * Displays the application information
	 */
	public void displayAboutMessage(){
		JOptionPane.showMessageDialog(MainScreen.contentPane, "Developed by Alvaro Morales " 
				+ "for Cementos Lima S.A.\n ©2010. All Rights Reserved", "Warehouse Application", 
				JOptionPane.INFORMATION_MESSAGE);
	}
	
}
